#!/bin/sh

# This script installs the Nix package manager on your system by
# downloading a binary distribution and running its installer script
# (which in turn creates and populates /nix).

tarball=nix-binary-tarball.tar.bz2
unpack=nix-binary-tarball-unpack

cleanup() {
    rm -rf "$unpack" "$tarball"
}

oops() {
    echo "$0: $@" >&2
    cleanup
    exit 1
}

case "$(uname -s).$(uname -m)" in
    Linux.x86_64) system=x86_64-linux;;
    Linux.i?86) system=i686-linux;;
    Darwin.x86_64) system=x86_64-darwin;;
    *) oops "sorry, there is no binary distribution of Nix for your platform";;
esac

url="https://nixos.org/releases/nix/nix-1.7/nix-1.7-$system.tar.bz2"

type curl > /dev/null 2>&1 || which curl > /dev/null 2>&1 ||
    oops "you do not have \`curl' installed," \
         "which I need to download the binary tarball"

echo "downloading Nix binary tarball for $system from \`$url'..."
curl -L -o "$tarball" "$url" || oops "failed to download \`$url'"

echo "unpacking binary tarball..."
mkdir "$unpack"
tar xf "$tarball" -C "$unpack"

[ -e "$unpack"/*/install ] ||
    oops "installation script is missing from the binary tarball!"

"$unpack"/*/install
cleanup
