#! /bin/sh

# This script installs the Nix package manager on your system by
# downloading a binary distribution and running its installer script
# (which in turn creates and populates /nix).

set -e

kernel=$(uname -s)
machine=$(uname -m)

if [ "$kernel" = Linux -a "$machine" = x86_64 ]; then
    system=x86_64-linux
elif [ "$kernel" = Linux -a "$machine" = i686 ]; then
    system=i686-linux
elif [ "$kernel" = Darwin -a "$machine" = x86_64 ]; then
    system=x86_64-darwin
else
    echo "$0: sorry, there is no binary distribution of Nix for your platform"
    exit 1
fi

url="https://hydra.nixos.org/job/nix/trunk/binaryTarball.$system/latest/download-by-type/file/binary-dist"

if ! type -p curl > /dev/null; then
    echo "$0: you do not have \`curl' installed, which I need to download the binary tarball"
    exit 1
fi

echo "downloading Nix binary tarball for $system from \`$url'..."
tarball=nix-binary-tarball.tar.bz2
if ! curl -L -o "$tarball" "$url"; then
    echo "$0: failed to download \`$url'"
    exit 1
fi

echo "unpacking binary tarball..."
unpack=nix-binary-tarball-unpack
rm -rf "$unpack"
mkdir "$unpack"
tar xf "$tarball" -C "$unpack"

if ! [ -e "$unpack"/*/install ]; then
    echo "$0: installation script is missing from the binary tarball!"
    exit 1
fi

"$unpack"/*/install

rm -rf "$unpack" "$tarball"
