version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
  groups:
    all:
      patterns:
        - "*"
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: "daily"
  open-pull-requests-limit: 1
  commit-message:
      prefix: "chore"
      include: "scope"
  groups:
    all:
      patterns:
        - "*"
