rules:
  dangerous-triggers:
    ignore:
      # since we need to run preview deployments we need these triggers on our pr pipeline
      # this can be removed if we find a better solution for preview deployments
      #
      # safety is ensured by completely separating the deploy-prod and deploy-pr workflows
      # leaving no chance to branch out from any PR identifying logic in a shared workflow
      - deploy-pr.yml