language: nix
os: linux
install:
  - nix-env -iA nixpkgs.nixFlakes
  - echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
script:
  - nix build
after_success:
  # direct push to master
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi
