language: nix
os: linux
env:
  global:
    - NIX_VERSION="2.3.3"
    - NIXOPS_VERSION="1.7"
    - LANGUAGE="en_US.UTF-8"
    - LC_ALL="en_US.UTF-8"
    - LC_CTYPE="en_US.UTF-8"
    - LANG="en_US.UTF-8"
install:
  - nix-shell shell.nix --command "echo DEPENDENCIES-INSTALLED"
script:
  # TODO: this should be moved into Makefile
  - git clone https://github.com/nixos/nix.git /tmp/nix && git --work-tree=/tmp/nix checkout $NIX_VERSION && cd nix && ln -s /tmp/nix/doc/manual manual-raw
  # TODO: this should be moved into Makefile
  - git clone https://github.com/nixos/nixops.git /tmp/nixops && git --work-tree=/tmp/nixops checkout $NIXOPS_VERSION && cd nixops && ln -s /tmp/nixops/doc/manual manual-raw
  - nix-shell shell.nix --command "make"
deploy:
  - provider: script
    cleanup: false
    script: nix-shell -p nodejs --command "pwd && env && npm install netlify-cli && ./node_modules/.bin/netlify deploy --json --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir ./ --prod"
    on:
      branch: master
