language: nix
os: linux
install:
  - nix-env -iA nixpkgs.nixFlakes
  - echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
script:
  - nix build
after_success:
  - ./publish.sh
