name: "Install dependencies"
description: "Install common nix dependencies"
inputs:
  cachix_signing_key:
    description: "Cachix signing key"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Installing Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install unstable channel
      shell: bash
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing NixFlakes
      shell: bash
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        nix --version
        cat /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - name: Setup Cachix
      if: "inputs.cachix_signing_key != ''"
      uses: cachix/cachix-action@v10
      with:
        name: nixos-homepage
        signingKey: '${{ inputs.cachix_signing_key }}'
