name: "Build & Deploy to Netlify"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
    - name: Installing Nix
      uses: cachix/install-nix-action@v7
    - name: Building nixos.org
      run: nix-build

