name: "Build & Deploy to Netlify"
on:
  pull_request:
  push:
  schedule:
  - cron: '0 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
    - name: Installing Nix
      uses: cachix/install-nix-action@v7
    - name: Update content
      run: UPDATE=1 nix-shell -p gnumake -p curl --command "make update"
    - name: Building nixos.org
      run: nix-build && mkdir build && cp ./result/* ./build/ -R
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.0.5
      with:
        publish-dir: './build'
        production-branch: master
        github-token: ${{ secrets.GH_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

