name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
    - name: Installing Nix
      uses: cachix/install-nix-action@v7
    - name: Installing NixFlakes
      run: nix-env -iA nixpkgs.nixFlakes && echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - name: Building
      run: nix build

