name: "Build & Deploy to Netlify"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
    - name: Installing Nix
      uses: cachix/install-nix-action@v7
    - name: Installing NixFlakes
      run: nix-env -iA nixpkgs.nixFlakes
    - name: Turning ON Flakes feature
      run: echo "experimental-features = nix-command flakes" | tee -a /etc/nix/nix.conf
    - name: Building
      run: nix build

