name: "Build & Deploy to Netlify"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing Nix
      uses: cachix/install-nix-action@v8
    - name: Installing NixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo "::add-path::$HOME/.nix-profile/bin"
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        nix --version
        cat /etc/nix/nix.conf
    - name: Update content
      run: ./update.sh
    - name: Building nixos.org
      run: |
        nix build
        mkdir build
        cp -RL ./result/* ./build/
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.0.5
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        publish-dir: './build'
        production-branch: 'master'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deploy from GitHub Actions'
      if: github.repository == 'NixOS/nixos-homepage'
